# Generated by Django 5.1.6 on 2025-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Height (m)')),
                ('width', models.FloatField(verbose_name='Width (m)')),
            ],
        ),
    ]
